<a href="https://colab.research.google.com/github/yejin-park/MachineLearning_J/blob/main/2_210720.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pandas as pd

#붓꽃 데이터 세트를 로딩합니다.
iris = load_iris()
# print('feature names''s shape:', len(iris.feature_names))
# print('feature names :', iris.feature_names)

# print('target names''s shape:', len(iris.target_names))
# print('target names :', iris.target_names)

# print('data shape :', iris.data.shape)
# print('data :', iris['data'])

# print('target shape :', iris.target.shape)
# print('target :', iris.target)

#iris.data는 Iris 데이터 세트에서 피처(feature)만으로 된 데이터를 numpy로 가지고 있습니다.
iris_data = iris.data


#iris.target은 붓꽃 데이터 세트에서 레이블(결정 값) 데이터를 numpy로 가지고 있습니다.
iris_label = iris.target
# print(iris_label)
# print(iris.target_names)

#붓꽃 데이터 세트를 자세히 보기 위해 dataframe으로 변환합니다.
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df.tail(10)
# print(iris_df.head(5))


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
140                6.7               3.1                5.6               2.4   
141                6.9               3.1                5.1               2.3   
142                5.8               2.7                5.1               1.9   
143                6.8               3.2                5.9               2.3   
144                6.7               3.3                5.7               2.5   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
140      2  
141      2  
142      2  
143      2  
144      2  
145      2  
146      2  
147      2  
148      2  
149      2

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label,test_size=0.2, random_state=50)
# print(X_train, X_test)
dt_clf = DecisionTreeClassifier(random_state=11)

#학습수행
dt_clf.fit(X_train, y_train)

#학습이 완료된 DecisionTreeClassfier 객체에서 테스트 데이터 세트로 예측 수행.
pred = dt_clf.predict(X_test)

from sklearn.metrics import accuracy_score
print('예측 정확도', accuracy_score(y_test, pred))


예측 정확도 0.9666666666666667
예측 정확도: 0.9667
교차 검증별 정확도
 [0.98 0.92 0.98]
평균 검증 정확도
 0.96


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

iris = load_iris()
iris_data = iris.data
iris_label = iris.target

X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=15)

dt_clf = DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))

scores = cross_val_score(dt_clf, iris_data, iris_label, scoring='accuracy', cv=5)
print('교차 검증별 정확도\n', np.round(scores,4))
print('평균 검증 정확도\n', np.round(np.mean(scores),4))


예측 정확도: 0.9667
교차 검증별 정확도
 [0.9667 0.9667 0.9    0.9667 1.    ]
평균 검증 정확도
 0.96


In [ ]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

iris = load_iris()
iris_data = iris.data
x_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

parameters = {'max_depth':[1,2,3], 'min_samples_split':[2,3]}
import pandas as pd

grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True)
grid_dtree.fit(x_train, y_train)
score_df = pd.DataFrame(grid_dtree.cv_results_)
print(score_df[['params','mean_test_score','rank_test_score']])


# dtree = DecisionTreeClassifier(max_depth=3, min_samples_split=3, random_state=11)
# dtree.fit(x_train, y_train)
# pred = dtree.predict(X_test)
# print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test, pred)))
print('최적 파라미터:', grid_dtree.best_params_)
print('최고 정확도:', grid_dtree.best_score_)

#GridSearchCV의 refit으로 이미 학습된 estimator 반환
estimator = grid_dtree.best_estimator_
## dtree = DecisionTreeClassifier(max_depth=3, min_samples_split=2).fit(x_train, y_train)
pred = estimator.predict(X_test)

#GridSearchCV의 best_estimator_는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
from sklearn.metrics import accuracy_score
print('예측 정확도', accuracy_score(y_test, pred))


from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값', labels)
print('인코딩 클래스', encoder.classes_)


                                     params  mean_test_score  rank_test_score
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1
최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
최고 정확도: 0.975
예측 정확도 0.9666666666666667
인코딩 변환값 [0 1 4 5 3 2 2]
인코딩 클래스 ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값', labels)
print('인코딩 클래스', encoder.classes_)

from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
labels = labels.reshape(-1,1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print(oh_labels.toarray())
print(oh_labels.shape)


import pandas as pd
df = pd.DataFrame({'items':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']})
df_dummary = pd.get_dummies(df)
print(df_dummary)




인코딩 변환값 [0 1 4 5 3 2 2]
인코딩 클래스 ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
(7, 6)
   items_TV  items_냉장고  items_믹서  items_선풍기  items_전자레인지  items_컴퓨터
0         1          0         0          0            0          0
1         0          1         0          0            0          0
2         0          0         0          0            1          0
3         0          0         0          0            0          1
4         0          0         0          1            0          0
5         0          0         1          0            0          0
6         0          0         1          0            0          0


In [ ]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
import pandas as pd

iris_set = load_iris()
iris_data = iris_set.data
irisDF = pd.DataFrame(data=iris_data, columns=iris_set.feature_names)

print(irisDF.mean())
print(irisDF.var())


sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


In [ ]:
scaler = StandardScaler()
scaler.fit(irisDF)
iris_scaled = scaler.transform(irisDF)

irisDF_scaled = pd.DataFrame(data=iris_scaled, columns=iris_set.feature_names)

print(irisDF_scaled.mean())
print(irisDF_scaled.var())


sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64
